//! DPoP proof validation for server-side (RFC 9449)
//!
//! Security hardening:
//! - JTI replay protection (RFC 9449 Section 11.1)
//! - Constant-time comparison for cryptographic values
//! - JWK coordinate length validation

use base64::{engine::general_purpose::URL_SAFE_NO_PAD, Engine};
use p256::ecdsa::{signature::Verifier, Signature, VerifyingKey};
use serde::Deserialize;
use sha2::{Digest, Sha256};
use std::time::{SystemTime, UNIX_EPOCH};
use subtle::ConstantTimeEq;
use thiserror::Error;

/// Expected coordinate length for P-256 (32 bytes)
const P256_COORDINATE_LEN: usize = 32;

/// ML-DSA-65 signature size (FIPS 204)
#[cfg(feature = "pqc")]
const ML_DSA_65_SIG_SIZE: usize = 3309;

/// ES256 raw r||s signature size
#[cfg(feature = "pqc")]
const ES256_SIG_SIZE: usize = 64;

/// ML-DSA-65 verifying key size (FIPS 204)
#[cfg(feature = "pqc")]
const ML_DSA_65_VK_SIZE: usize = 1952;

/// Maximum entries in the DPoP JTI cache before forced cleanup/rejection
/// This prevents memory exhaustion attacks where an attacker submits many unique JTIs
/// Constant-time string comparison for cryptographic values
fn constant_time_eq(a: &str, b: &str) -> bool {
    if a.len() != b.len() {
        return false;
    }
    a.as_bytes().ct_eq(b.as_bytes()).into()
}

/// DPoP proof claims
#[derive(Debug, Deserialize)]
#[cfg_attr(test, derive(serde::Serialize))]
pub struct DPoPProofClaims {
    pub jti: String,
    pub htm: String,
    pub htu: String,
    pub iat: i64,
    #[serde(default)]
    pub nonce: Option<String>,
}

/// JWK embedded in DPoP proof header
#[derive(Debug, Deserialize)]
pub struct EcJwk {
    pub kty: String,
    pub crv: String,
    pub x: String,
    pub y: String,
}

/// DPoP validation configuration
#[derive(Debug, Clone)]
pub struct DPoPConfig {
    /// Maximum age of proof in seconds (default: 60).
    /// Maps to `AgentConfig.timeouts.clock_skew_staleness_secs`.
    pub max_proof_age: u64,
    /// Clock skew tolerance for proofs issued in the future (seconds, default: 5).
    ///
    /// A proof with `iat > now + clock_skew_future_secs` is rejected. This prevents
    /// accepting proofs from a client whose clock is significantly ahead of the server.
    ///
    /// Maps to `AgentConfig.timeouts.clock_skew_future_secs`.
    pub clock_skew_future_secs: u64,
    /// Whether nonce is required
    pub require_nonce: bool,
    /// Expected nonce value (if require_nonce is true)
    pub expected_nonce: Option<String>,
    /// Expected method (e.g., "SSH", "POST")
    pub expected_method: String,
    /// Expected target (hostname or URL)
    pub expected_target: String,
}

impl Default for DPoPConfig {
    fn default() -> Self {
        Self {
            max_proof_age: 60,
            clock_skew_future_secs: 5,
            require_nonce: false,
            expected_nonce: None,
            expected_method: "SSH".to_string(),
            expected_target: String::new(),
        }
    }
}

#[derive(Debug, Error)]
pub enum DPoPValidationError {
    #[error("Invalid proof format")]
    InvalidFormat,
    #[error("Invalid header")]
    InvalidHeader(String),
    #[error("Invalid signature")]
    InvalidSignature,
    #[error("Missing JWK in header")]
    MissingJwk,
    #[error("Unsupported algorithm")]
    UnsupportedAlgorithm(String),
    #[error("Proof expired")]
    ProofExpired { iat: i64, now: i64 },
    #[error("Method mismatch")]
    MethodMismatch { expected: String, actual: String },
    #[error("Target mismatch")]
    TargetMismatch { expected: String, actual: String },
    #[error("Nonce mismatch")]
    NonceMismatch,
    #[error("Missing nonce")]
    MissingNonce,
    #[error("Thumbprint mismatch")]
    ThumbprintMismatch {
        token_jkt: String,
        proof_jkt: String,
    },
    #[error("Token missing cnf.jkt claim")]
    MissingTokenBinding,
    #[error("Base64 decode error")]
    Base64Error,
    #[error("JSON parse error")]
    JsonError(String),
    #[error("DPoP proof replay detected")]
    ReplayDetected,
    #[error("Invalid JWK key parameters")]
    InvalidKeyParameters,
}

/// Result of a successful DPoP proof validation.
///
/// Contains the JWK thumbprint (for binding verification against `cnf.jkt`),
/// the nonce extracted from the proof claims (for cache-based single-use enforcement),
/// and optional hardware attestation evidence from the JWT header (ADR-018).
#[derive(Debug, Clone)]
pub struct DPoPProofResult {
    /// JWK thumbprint of the key that signed the proof (RFC 7638).
    /// Compare against the access token's `cnf.jkt` claim.
    pub thumbprint: String,
    /// Nonce from the DPoP proof claims, if present.
    /// Used by auth.rs for cache-based single-use enforcement (RFC 9449 §8).
    pub nonce: Option<String>,
    /// Hardware attestation evidence from the `attest` header field (ADR-018).
    /// Present when the DPoP proof was generated by a TPM-backed signer.
    /// Verified by `verify_attestation_optional()` in the auth flow.
    pub attestation: Option<crate::oidc::attestation::AttestationEvidence>,
    /// Public key JWK from the DPoP proof header.
    ///
    /// Used by TPM attestation verification to reconstruct the certified key Name.
    pub public_key_jwk: serde_json::Value,
}

/// Validate a DPoP proof and return the JWK thumbprint and nonce.
///
/// Returns a [`DPoPProofResult`] containing:
/// - `thumbprint`: the public key thumbprint (compare against `cnf.jkt`)
/// - `nonce`: the nonce from the proof claims, if any
pub fn validate_dpop_proof(
    proof: &str,
    config: &DPoPConfig,
) -> Result<DPoPProofResult, DPoPValidationError> {
    // Split proof into parts
    let parts: Vec<&str> = proof.split('.').collect();
    if parts.len() != 3 {
        return Err(DPoPValidationError::InvalidFormat);
    }

    // Decode header
    let header_bytes = URL_SAFE_NO_PAD
        .decode(parts[0])
        .map_err(|_| DPoPValidationError::Base64Error)?;
    let header: serde_json::Value = serde_json::from_slice(&header_bytes)
        .map_err(|e| DPoPValidationError::JsonError(e.to_string()))?;

    // Verify typ
    if header.get("typ").and_then(|v| v.as_str()) != Some("dpop+jwt") {
        return Err(DPoPValidationError::InvalidHeader(
            "typ must be dpop+jwt".to_string(),
        ));
    }

    // Verify alg
    let alg = header
        .get("alg")
        .and_then(|v| v.as_str())
        .ok_or_else(|| DPoPValidationError::InvalidHeader("missing alg".to_string()))?;

    // Dispatch based on algorithm
    let message = format!("{}.{}", parts[0], parts[1]);
    let signature_bytes = URL_SAFE_NO_PAD
        .decode(parts[2])
        .map_err(|_| DPoPValidationError::Base64Error)?;

    let jwk_value = header
        .get("jwk")
        .ok_or(DPoPValidationError::MissingJwk)?
        .clone();

    let thumbprint = match alg {
        "ES256" => {
            let jwk: EcJwk = serde_json::from_value(jwk_value.clone())
                .map_err(|e| DPoPValidationError::JsonError(e.to_string()))?;
            let verifying_key = jwk_to_verifying_key(&jwk)?;
            let signature = Signature::from_slice(&signature_bytes)
                .map_err(|_| DPoPValidationError::InvalidSignature)?;
            verifying_key
                .verify(message.as_bytes(), &signature)
                .map_err(|_| DPoPValidationError::InvalidSignature)?;
            compute_jwk_thumbprint(&jwk)
        }
        #[cfg(feature = "pqc")]
        "ML-DSA-65-ES256" => {
            validate_composite_proof(&jwk_value, message.as_bytes(), &signature_bytes)?
        }
        _ => return Err(DPoPValidationError::UnsupportedAlgorithm(alg.to_string())),
    };

    // Decode claims
    let claims_bytes = URL_SAFE_NO_PAD
        .decode(parts[1])
        .map_err(|_| DPoPValidationError::Base64Error)?;
    let claims: DPoPProofClaims = serde_json::from_slice(&claims_bytes)
        .map_err(|e| DPoPValidationError::JsonError(e.to_string()))?;

    // Validate iat (proof age)
    // If system time is before 1970-01-01 (severely misconfigured clock), we default to
    // duration 0. This causes the proof age check to fail naturally (proof will appear
    // very old), which is the correct security-conservative behavior — no panic in PAM.
    let now = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_secs() as i64;

    if now - claims.iat > config.max_proof_age as i64 {
        return Err(DPoPValidationError::ProofExpired {
            iat: claims.iat,
            now,
        });
    }

    // Don't accept proofs from the future (with small clock skew allowance).
    // Security: clock_skew_future_secs is operator-configurable (default 5s).
    // Accepting proofs too far in the future weakens replay protection.
    if claims.iat > now + config.clock_skew_future_secs as i64 {
        return Err(DPoPValidationError::ProofExpired {
            iat: claims.iat,
            now,
        });
    }

    // Validate method
    if claims.htm != config.expected_method {
        return Err(DPoPValidationError::MethodMismatch {
            expected: config.expected_method.clone(),
            actual: claims.htm,
        });
    }

    // Validate target
    if claims.htu != config.expected_target {
        return Err(DPoPValidationError::TargetMismatch {
            expected: config.expected_target.clone(),
            actual: claims.htu,
        });
    }

    // Validate nonce (constant-time comparison to prevent timing attacks)
    if config.require_nonce {
        match (&claims.nonce, &config.expected_nonce) {
            (Some(proof_nonce), Some(expected_nonce)) => {
                if !constant_time_eq(proof_nonce, expected_nonce) {
                    return Err(DPoPValidationError::NonceMismatch);
                }
            }
            (None, _) => return Err(DPoPValidationError::MissingNonce),
            _ => {}
        }
    }

    // JTI replay protection (RFC 9449 Section 11.1)
    // TTL = max_proof_age + 5 seconds (for clock skew)
    //
    // Phase 30 (D-05): DPoP proof JTI uses the same FsAtomicStore as access
    // token JTI for cross-fork replay protection. "dpop" is used as the scope
    // so DPoP proof JTIs are isolated from access token JTIs in the filesystem
    // directory. DPoP binding is a HARD-FAIL check (CLAUDE.md §Security
    // Invariants): IoError is treated identically to a replay — authentication
    // fails closed rather than open.
    let jti_ttl = config.max_proof_age + 5;
    let jti_expires_at = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap_or_default()
        .as_secs()
        .saturating_add(jti_ttl);

    {
        use crate::security::fs_store::AtomicRecordResult;
        let jti_store = crate::security::jti_cache::global_jti_store();
        match jti_store.check_and_record("dpop", &claims.jti, jti_expires_at) {
            AtomicRecordResult::New => { /* proceed — first use of this proof JTI */ }
            AtomicRecordResult::AlreadyExists => {
                tracing::warn!(
                    jti = %claims.jti,
                    "DPoP proof JTI replay detected"
                );
                return Err(DPoPValidationError::ReplayDetected);
            }
            AtomicRecordResult::IoError(e) => {
                // DPoP proof replay protection is HARD-FAIL per CLAUDE.md.
                // Filesystem unavailability is treated as a replay rather than
                // falling back to the per-process cache — an attacker who can
                // remove the tmpfiles directory should not gain cross-fork replay.
                tracing::error!(
                    error = %e,
                    jti = %claims.jti,
                    "DPoP proof JTI filesystem store unavailable - hard-failing (replay)"
                );
                return Err(DPoPValidationError::ReplayDetected);
            }
        }
    }

    // Extract attestation evidence from the `attest` header field (ADR-018).
    // Best-effort: if the field is missing or malformed, attestation is None.
    // The caller (apply_per_issuer_dpop) decides enforcement via verify_attestation_optional().
    let attestation: Option<crate::oidc::attestation::AttestationEvidence> =
        header.get("attest").and_then(|v| {
            serde_json::from_value(v.clone())
                .map_err(|e| {
                    tracing::warn!(
                        error = %e,
                        "Failed to deserialize attestation evidence from DPoP header — ignoring"
                    );
                })
                .ok()
        });

    let nonce = claims.nonce;
    Ok(DPoPProofResult {
        thumbprint,
        nonce,
        attestation,
        public_key_jwk: jwk_value,
    })
}

/// Verify that the proof's key matches the token's cnf.jkt claim
/// Uses constant-time comparison to prevent timing attacks
pub fn verify_dpop_binding(
    proof_thumbprint: &str,
    token_jkt: &str,
) -> Result<(), DPoPValidationError> {
    // Use constant-time comparison to prevent timing attacks
    if !constant_time_eq(proof_thumbprint, token_jkt) {
        return Err(DPoPValidationError::ThumbprintMismatch {
            token_jkt: token_jkt.to_string(),
            proof_jkt: proof_thumbprint.to_string(),
        });
    }
    Ok(())
}

fn jwk_to_verifying_key(jwk: &EcJwk) -> Result<VerifyingKey, DPoPValidationError> {
    if jwk.kty != "EC" || jwk.crv != "P-256" {
        return Err(DPoPValidationError::UnsupportedAlgorithm(format!(
            "kty={}, crv={}",
            jwk.kty, jwk.crv
        )));
    }

    let x_bytes = URL_SAFE_NO_PAD
        .decode(&jwk.x)
        .map_err(|_| DPoPValidationError::Base64Error)?;
    let y_bytes = URL_SAFE_NO_PAD
        .decode(&jwk.y)
        .map_err(|_| DPoPValidationError::Base64Error)?;

    // Validate coordinate lengths for P-256 (32 bytes each)
    if x_bytes.len() != P256_COORDINATE_LEN || y_bytes.len() != P256_COORDINATE_LEN {
        return Err(DPoPValidationError::InvalidKeyParameters);
    }

    // Build uncompressed point: 0x04 || x || y
    let mut point_bytes = vec![0x04];
    point_bytes.extend_from_slice(&x_bytes);
    point_bytes.extend_from_slice(&y_bytes);

    VerifyingKey::from_sec1_bytes(&point_bytes).map_err(|_| DPoPValidationError::InvalidSignature)
}

fn compute_jwk_thumbprint(jwk: &EcJwk) -> String {
    // RFC 7638: canonical JSON with lexicographic member ordering
    // For EC P-256: crv < kty < x < y
    //
    // Security: Use hardcoded canonical values for kty and crv instead of
    // user-supplied values. We only support ES256 (P-256), so these are fixed.
    // This prevents potential thumbprint manipulation via non-canonical values.
    // The actual kty/crv values are validated in jwk_to_verifying_key() before
    // this function is called.
    let canonical = format!(
        r#"{{"crv":"P-256","kty":"EC","x":"{}","y":"{}"}}"#,
        jwk.x, jwk.y
    );

    let hash = Sha256::digest(canonical.as_bytes());
    URL_SAFE_NO_PAD.encode(hash)
}

/// Validate a composite ML-DSA-65+ES256 DPoP proof signature.
///
/// Verifies both the ML-DSA-65 and ES256 components of the composite signature.
/// Returns the composite JWK thumbprint on success.
///
/// Composite signature format (draft-ietf-jose-pq-composite-sigs-01):
/// `2-byte BE length of ML-DSA sig || ML-DSA-65 sig (3309 bytes) || ES256 sig (64 bytes)`
#[cfg(feature = "pqc")]
fn validate_composite_proof(
    jwk_value: &serde_json::Value,
    message: &[u8],
    signature_bytes: &[u8],
) -> Result<String, DPoPValidationError> {
    // Parse composite JWK
    let pq_jwk = jwk_value
        .get("pq")
        .ok_or_else(|| DPoPValidationError::InvalidHeader("missing pq component in JWK".into()))?;
    let trad_jwk = jwk_value.get("trad").ok_or_else(|| {
        DPoPValidationError::InvalidHeader("missing trad component in JWK".into())
    })?;

    // Validate kty
    if jwk_value.get("kty").and_then(|v| v.as_str()) != Some("COMPOSITE") {
        return Err(DPoPValidationError::InvalidKeyParameters);
    }

    // Extract and validate traditional EC key
    let ec_jwk: EcJwk = serde_json::from_value(trad_jwk.clone())
        .map_err(|e| DPoPValidationError::JsonError(e.to_string()))?;
    let ec_vk = jwk_to_verifying_key(&ec_jwk)?;

    // Extract ML-DSA-65 public key
    let pq_pub_b64 = pq_jwk
        .get("pub")
        .and_then(|v| v.as_str())
        .ok_or(DPoPValidationError::InvalidKeyParameters)?;
    let pq_pub_bytes = URL_SAFE_NO_PAD
        .decode(pq_pub_b64)
        .map_err(|_| DPoPValidationError::Base64Error)?;
    if pq_pub_bytes.len() != ML_DSA_65_VK_SIZE {
        return Err(DPoPValidationError::InvalidKeyParameters);
    }

    let pq_vk_encoded =
        ml_dsa::EncodedVerifyingKey::<ml_dsa::MlDsa65>::try_from(pq_pub_bytes.as_slice())
            .map_err(|_| DPoPValidationError::InvalidKeyParameters)?;
    let pq_vk = ml_dsa::VerifyingKey::<ml_dsa::MlDsa65>::decode(&pq_vk_encoded);

    // Parse composite signature: 2-byte BE length + ML-DSA sig + ES256 sig
    let min_len = 2 + ML_DSA_65_SIG_SIZE + ES256_SIG_SIZE;
    if signature_bytes.len() < min_len {
        return Err(DPoPValidationError::InvalidSignature);
    }

    let pq_len = u16::from_be_bytes([signature_bytes[0], signature_bytes[1]]) as usize;
    if pq_len != ML_DSA_65_SIG_SIZE {
        return Err(DPoPValidationError::InvalidSignature);
    }
    if signature_bytes.len() != 2 + pq_len + ES256_SIG_SIZE {
        return Err(DPoPValidationError::InvalidSignature);
    }

    let pq_sig_bytes = &signature_bytes[2..2 + pq_len];
    let ec_sig_bytes = &signature_bytes[2 + pq_len..];

    // Verify ML-DSA-65 signature
    use ml_dsa::signature::Verifier as MlDsaVerifier;
    let pq_sig = ml_dsa::Signature::<ml_dsa::MlDsa65>::try_from(pq_sig_bytes)
        .map_err(|_| DPoPValidationError::InvalidSignature)?;
    pq_vk
        .verify(message, &pq_sig)
        .map_err(|_| DPoPValidationError::InvalidSignature)?;

    // Verify ES256 signature
    let ec_sig =
        Signature::from_slice(ec_sig_bytes).map_err(|_| DPoPValidationError::InvalidSignature)?;
    ec_vk
        .verify(message, &ec_sig)
        .map_err(|_| DPoPValidationError::InvalidSignature)?;

    // Compute composite thumbprint
    let pq_pub = URL_SAFE_NO_PAD.encode(&pq_pub_bytes);
    let canonical = format!(
        r#"{{"alg":"ML-DSA-65-ES256","kty":"COMPOSITE","pq":{{"alg":"ML-DSA-65","kty":"AKP","pub":"{pq_pub}"}},"trad":{{"crv":"P-256","kty":"EC","x":"{}","y":"{}"}}}}"#,
        ec_jwk.x, ec_jwk.y
    );
    let hash = Sha256::digest(canonical.as_bytes());
    Ok(URL_SAFE_NO_PAD.encode(hash))
}

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::expect_used)]
mod tests {
    use super::*;
    use p256::ecdsa::{signature::Signer, SigningKey};
    use p256::elliptic_curve::rand_core::OsRng;

    // ── Test isolation for filesystem JTI store ───────────────────────────────
    //
    // All test modules must use the shared `setup_test_jti_dir()` from
    // `jti_cache.rs` to avoid racing on `PRMANA_JTI_DIR`. The Lazy
    // reads the env var exactly once — independent OnceLock per module
    // caused spurious `ReplayDetected` when tests ran in parallel.
    use crate::security::jti_cache::setup_test_jti_dir;

    fn setup_jti_dir() {
        setup_test_jti_dir();
    }

    // Helper to create a test proof.
    // Also ensures the JTI filesystem store is redirected to a tempdir so
    // tests do not fail due to a missing/unwritable /run/prmana/jti/.
    fn create_test_proof(method: &str, target: &str, nonce: Option<&str>) -> (String, String) {
        setup_jti_dir();
        let signing_key = SigningKey::random(&mut OsRng);
        let verifying_key = signing_key.verifying_key();
        let point = verifying_key.to_encoded_point(false);

        let x = URL_SAFE_NO_PAD.encode(point.x().unwrap());
        let y = URL_SAFE_NO_PAD.encode(point.y().unwrap());

        let jwk = EcJwk {
            kty: "EC".to_string(),
            crv: "P-256".to_string(),
            x: x.clone(),
            y: y.clone(),
        };

        let now = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap()
            .as_secs() as i64;

        let claims = DPoPProofClaims {
            jti: uuid::Uuid::new_v4().to_string(),
            htm: method.to_string(),
            htu: target.to_string(),
            iat: now,
            nonce: nonce.map(String::from),
        };

        let header_json = serde_json::json!({
            "typ": "dpop+jwt",
            "alg": "ES256",
            "jwk": {
                "kty": "EC",
                "crv": "P-256",
                "x": x,
                "y": y
            }
        });

        let header_b64 = URL_SAFE_NO_PAD.encode(header_json.to_string().as_bytes());
        let claims_b64 = URL_SAFE_NO_PAD.encode(serde_json::to_string(&claims).unwrap().as_bytes());

        let message = format!("{header_b64}.{claims_b64}");

        let signature: Signature = signing_key.sign(message.as_bytes());
        let sig_b64 = URL_SAFE_NO_PAD.encode(signature.to_bytes());

        let proof = format!("{message}.{sig_b64}");
        let thumbprint = compute_jwk_thumbprint(&jwk);

        (proof, thumbprint)
    }

    #[test]
    fn test_validate_valid_proof() {
        let (proof, _thumbprint) = create_test_proof("SSH", "server.example.com", None);

        let config = DPoPConfig {
            max_proof_age: 60,
            clock_skew_future_secs: 5,
            require_nonce: false,
            expected_nonce: None,
            expected_method: "SSH".to_string(),
            expected_target: "server.example.com".to_string(),
        };

        let result = validate_dpop_proof(&proof, &config);
        assert!(result.is_ok());
        // nonce should be None for a proof without nonce claim
        assert!(result.unwrap().nonce.is_none());
    }

    #[test]
    fn test_validate_proof_with_nonce() {
        let (proof, _) = create_test_proof("SSH", "server.example.com", Some("abc123"));

        let config = DPoPConfig {
            max_proof_age: 60,
            clock_skew_future_secs: 5,
            require_nonce: true,
            expected_nonce: Some("abc123".to_string()),
            expected_method: "SSH".to_string(),
            expected_target: "server.example.com".to_string(),
        };

        let result = validate_dpop_proof(&proof, &config);
        assert!(result.is_ok());
        let dpop_result = result.unwrap();
        assert_eq!(dpop_result.nonce.as_deref(), Some("abc123"));
    }

    #[test]
    fn test_dpop_proof_result_has_thumbprint_and_nonce() {
        let (proof, expected_thumbprint) =
            create_test_proof("SSH", "result-test.example.com", Some("my-nonce-xyz"));

        let config = DPoPConfig {
            max_proof_age: 60,
            clock_skew_future_secs: 5,
            require_nonce: false, // let the result carry nonce without validating it here
            expected_nonce: None,
            expected_method: "SSH".to_string(),
            expected_target: "result-test.example.com".to_string(),
        };

        let result = validate_dpop_proof(&proof, &config).unwrap();
        assert_eq!(
            result.thumbprint, expected_thumbprint,
            "thumbprint must match"
        );
        assert_eq!(
            result.nonce.as_deref(),
            Some("my-nonce-xyz"),
            "nonce must be carried from proof claims"
        );
    }

    #[test]
    fn test_reject_wrong_method() {
        let (proof, _) = create_test_proof("POST", "server.example.com", None);

        let config = DPoPConfig {
            max_proof_age: 60,
            clock_skew_future_secs: 5,
            require_nonce: false,
            expected_nonce: None,
            expected_method: "SSH".to_string(),
            expected_target: "server.example.com".to_string(),
        };

        let result = validate_dpop_proof(&proof, &config);
        assert!(matches!(
            result,
            Err(DPoPValidationError::MethodMismatch { .. })
        ));
    }

    #[test]
    fn test_reject_wrong_target() {
        let (proof, _) = create_test_proof("SSH", "other.example.com", None);

        let config = DPoPConfig {
            max_proof_age: 60,
            clock_skew_future_secs: 5,
            require_nonce: false,
            expected_nonce: None,
            expected_method: "SSH".to_string(),
            expected_target: "server.example.com".to_string(),
        };

        let result = validate_dpop_proof(&proof, &config);
        assert!(matches!(
            result,
            Err(DPoPValidationError::TargetMismatch { .. })
        ));
    }

    #[test]
    fn test_reject_wrong_nonce() {
        let (proof, _) = create_test_proof("SSH", "server.example.com", Some("wrong"));

        let config = DPoPConfig {
            max_proof_age: 60,
            clock_skew_future_secs: 5,
            require_nonce: true,
            expected_nonce: Some("correct".to_string()),
            expected_method: "SSH".to_string(),
            expected_target: "server.example.com".to_string(),
        };

        let result = validate_dpop_proof(&proof, &config);
        assert!(matches!(result, Err(DPoPValidationError::NonceMismatch)));
    }

    #[test]
    fn test_verify_dpop_binding() {
        let (proof, thumbprint) = create_test_proof("SSH", "server.example.com", None);

        let config = DPoPConfig {
            max_proof_age: 60,
            clock_skew_future_secs: 5,
            require_nonce: false,
            expected_nonce: None,
            expected_method: "SSH".to_string(),
            expected_target: "server.example.com".to_string(),
        };

        let result = validate_dpop_proof(&proof, &config).unwrap();

        // Should match
        assert!(verify_dpop_binding(&result.thumbprint, &thumbprint).is_ok());

        // Should not match different thumbprint
        assert!(verify_dpop_binding(&result.thumbprint, "wrong-thumbprint").is_err());
    }

    #[test]
    fn test_replay_detection() {
        setup_jti_dir();
        // Create a proof with a specific JTI
        let signing_key = SigningKey::random(&mut OsRng);
        let verifying_key = signing_key.verifying_key();
        let point = verifying_key.to_encoded_point(false);

        let x = URL_SAFE_NO_PAD.encode(point.x().unwrap());
        let y = URL_SAFE_NO_PAD.encode(point.y().unwrap());

        let now = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap()
            .as_secs() as i64;

        // Use a fixed JTI for this test
        let fixed_jti = format!("replay-test-{now}");

        let claims = DPoPProofClaims {
            jti: fixed_jti.clone(),
            htm: "SSH".to_string(),
            htu: "replay-test.example.com".to_string(),
            iat: now,
            nonce: None,
        };

        let header_json = serde_json::json!({
            "typ": "dpop+jwt",
            "alg": "ES256",
            "jwk": {
                "kty": "EC",
                "crv": "P-256",
                "x": x,
                "y": y
            }
        });

        let header_b64 = URL_SAFE_NO_PAD.encode(header_json.to_string().as_bytes());
        let claims_b64 = URL_SAFE_NO_PAD.encode(serde_json::to_string(&claims).unwrap().as_bytes());

        let message = format!("{header_b64}.{claims_b64}");
        let signature: Signature = signing_key.sign(message.as_bytes());
        let sig_b64 = URL_SAFE_NO_PAD.encode(signature.to_bytes());

        let proof = format!("{message}.{sig_b64}");

        let config = DPoPConfig {
            max_proof_age: 60,
            clock_skew_future_secs: 5,
            require_nonce: false,
            expected_nonce: None,
            expected_method: "SSH".to_string(),
            expected_target: "replay-test.example.com".to_string(),
        };

        // First use should succeed
        let result1 = validate_dpop_proof(&proof, &config);
        assert!(result1.is_ok(), "First use should succeed");

        // Second use with same JTI should be detected as replay
        let result2 = validate_dpop_proof(&proof, &config);
        assert!(
            matches!(result2, Err(DPoPValidationError::ReplayDetected)),
            "Second use should be detected as replay"
        );
    }

    #[test]
    fn test_constant_time_eq() {
        // Test the constant-time comparison function
        assert!(constant_time_eq("hello", "hello"));
        assert!(!constant_time_eq("hello", "world"));
        assert!(!constant_time_eq("hello", "hell")); // Different lengths
        assert!(!constant_time_eq("", "x"));
        assert!(constant_time_eq("", ""));
    }
}
