APT::FTPArchive::Release::Origin "prmana";
APT::FTPArchive::Release::Label "prmana";
APT::FTPArchive::Release::Suite "stable";
APT::FTPArchive::Release::Codename "stable";
APT::FTPArchive::Release::Architectures "amd64 arm64";
APT::FTPArchive::Release::Components "main";
APT::FTPArchive::Release::Description "prmana package repository";
