name: Feature Request
description: Suggest a new feature for unix-oidc
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please describe your idea below.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: I would like unix-oidc to...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any alternative solutions or workarounds you've considered
      placeholder: I've also considered...

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component would this affect?
      options:
        - PAM Module (pam-unix-oidc)
        - Client Agent (unix-oidc-agent)
        - Policy Engine
        - Device Flow
        - DPoP
        - Documentation
        - CI/CD
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority (from your perspective)
      options:
        - Nice to have
        - Important for my use case
        - Critical blocker

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or references
      placeholder: |
        - Related RFC or standard: ...
        - Similar feature in other tools: ...

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I would be willing to contribute this feature
        - label: I would be willing to help test this feature
