# ---------------------------------------------------------------------------
# Network resources: ephemeral keypair + dedicated security group per run.
#
# Design decisions:
# - Use the default VPC (no VPC creation) — keeps the module minimal per
#   the design doc §4 requirement.
# - Security group is run-scoped (keyed by github_run_id) to avoid collisions
#   between concurrent runs and to simplify teardown verification.
# - A new keypair is created per run from the ephemeral pubkey generated by
#   the fleet-test workflow. This avoids storing long-lived keypair secrets.
# ---------------------------------------------------------------------------

# Default VPC data source — the module does not create networking, only
# resources inside the existing default VPC.
data "aws_vpc" "default" {
  default = true
}

# ---------------------------------------------------------------------------
# Ephemeral SSH keypair (T-DT0-01-04)
# Public key is injected from a workflow-generated ephemeral keypair.
# The private key never leaves the workflow runner.
# ---------------------------------------------------------------------------
resource "aws_key_pair" "fleet" {
  key_name   = "prmana-ci-${var.github_run_id}"
  public_key = var.ssh_public_key

  tags = {
    GitHubRun = var.github_run_id
  }
}

# ---------------------------------------------------------------------------
# Security group — run-scoped, dedicated to this fleet.
# Intentionally separate from the legacy "unix-oidc-ci-test-instances" SG
# to avoid cross-contamination with other CI workflows.
# ---------------------------------------------------------------------------
resource "aws_security_group" "fleet" {
  name        = "prmana-ci-fleet-${var.github_run_id}"
  description = "Ephemeral SG for prmana-ci fleet run ${var.github_run_id}. Auto-deleted on terraform destroy."
  vpc_id      = data.aws_vpc.default.id

  # Inbound SSH — restricted to allowed_ssh_cidr (default: 0.0.0.0/0 for CI).
  # README documents this as CI-only and references the variable for tightening.
  ingress {
    description = "SSH for test harness log collection"
    from_port   = 22
    to_port     = 22
    protocol    = "tcp"
    cidr_blocks = [var.allowed_ssh_cidr]
  }

  # Outbound: unrestricted — instances need to reach package mirrors,
  # the OIDC test stack, and AWS APIs.
  egress {
    description = "All outbound"
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }

  tags = {
    GitHubRun = var.github_run_id
  }

  # Prevent destroy-before-create ordering issues if the SG is still
  # attached to running instances during a re-apply.
  lifecycle {
    create_before_destroy = true
  }
}
