variable "distro" {
  type        = string
  description = "Linux distribution to deploy. Must be one of the locked distro×arch matrix values."

  validation {
    condition = contains(
      ["debian-12", "ubuntu-22.04", "ubuntu-24.04", "rocky-9", "amazonlinux-2023", "fedora-40"],
      var.distro
    )
    error_message = "distro must be one of: debian-12, ubuntu-22.04, ubuntu-24.04, rocky-9, amazonlinux-2023, fedora-40."
  }
}

variable "arch" {
  type        = string
  description = "CPU architecture. Must be amd64 or arm64. Note: fedora-40 only supports amd64."

  validation {
    condition     = contains(["amd64", "arm64"], var.arch)
    error_message = "arch must be amd64 or arm64."
  }
}

variable "instance_count" {
  type        = number
  description = "Number of spot instances to provision. Maximum 10 to cap blast radius."

  validation {
    condition     = var.instance_count >= 1 && var.instance_count <= 10
    error_message = "instance_count must be between 1 and 10 (inclusive)."
  }
}

variable "max_instance_minutes" {
  type        = number
  default     = 30
  description = "Hard upper bound on instance lifetime in minutes. The user-data watchdog issues shutdown -h +N at launch time. Combined with instance_initiated_shutdown_behavior=terminate, the instance is fully destroyed when this timer fires."

  validation {
    condition     = var.max_instance_minutes >= 5 && var.max_instance_minutes <= 120
    error_message = "max_instance_minutes must be between 5 and 120."
  }
}

variable "budget_limit_usd" {
  type        = number
  default     = 5
  description = "AWS Budget cost cap in USD per GitHub run. An SNS notification fires at 80% of this threshold. This is a backstop — the instance watchdog and workflow-level teardown are the primary controls."
}

variable "github_run_id" {
  type        = string
  description = "GitHub Actions run ID. Used to tag all resources for attribution and scoped cost tracking. Passed by the fleet-test workflow automatically."
}

variable "aws_region" {
  type        = string
  default     = "us-west-2"
  description = "AWS region to deploy fleet. Must match the region where the existing OIDC federation role and instance profile reside."
}

variable "instance_type_amd64" {
  type        = string
  default     = "t3a.small"
  description = "EC2 instance type for amd64 (x86_64) instances. t3a.small is ~$0.005/hr spot in us-west-2."
}

variable "instance_type_arm64" {
  type        = string
  default     = "t4g.small"
  description = "EC2 instance type for arm64 (Graviton) instances. t4g.small is ~$0.005/hr spot in us-west-2."
}

variable "sns_budget_topic_arn" {
  type        = string
  default     = ""
  description = "Optional SNS topic ARN for budget alarm notifications. If empty, the budget is created without a subscriber (alarm still fires in AWS Console). Leave empty in ad-hoc runs; set in fleet-test.yml for automated alerts."
}

variable "ssh_public_key" {
  type        = string
  description = "RSA or Ed25519 public key material (the text that goes into authorized_keys). Injected from an ephemeral keypair generated by the fleet-test workflow. Required for SSH log collection in plan DT-0-04."
  sensitive   = true
}

variable "allowed_ssh_cidr" {
  type        = string
  default     = "0.0.0.0/0"
  description = "CIDR block allowed inbound SSH (port 22) access. Defaults to 0.0.0.0/0 for CI convenience. IMPORTANT: this module is CI-only. For production use (which is explicitly a non-goal), restrict to your GitHub Actions runner IP ranges."
}

variable "vpc_id" {
  type        = string
  default     = ""
  description = "Explicit VPC ID to place fleet resources in. When set, the data.aws_vpc.default lookup is skipped (avoids ec2:DescribeVpcAttribute). The fleet-test workflow resolves this via 'aws ec2 describe-vpcs' (only ec2:DescribeVpcs needed). Leave empty only when running with a role that has ec2:DescribeVpcAttribute."
}

# ---------------------------------------------------------------------------
# Cross-variable precondition: fedora-40 + arm64 is not in the supported matrix.
# Terraform requires preconditions to be on a resource or output, so this is
# enforced in ami.tf via a null_resource check or in outputs.tf via a lifecycle
# precondition. The distro and arch validations above cover individual values;
# the combination check is in ami.tf locals.
# ---------------------------------------------------------------------------
