//! Session record lifecycle management for PAM module.
//!
//! This module provides atomic JSON session records written to a tmpfs directory
//! (default: `/run/prmana/sessions/`) for bounded session lifetime tracking.
//!
//! Session records are written by `pam_sm_open_session` and deleted by
//! `pam_sm_close_session`. The agent daemon uses them to track active sessions
//! for introspection and revocation checks.
//!
//! ## Security properties
//!
//! - Session files are 0600 (owner: root, since sshd runs as root at session open)
//! - Session directory is 0700 (owner: root)
//! - Write is atomic: write to `{id}.json.tmp`, set permissions, rename to `{id}.json`
//! - Path traversal prevention: session IDs are validated before file operations
//! - Delete returns the parsed record so callers can compute session duration

use serde::{Deserialize, Serialize};
use std::fs;
use std::io::{self, Write};
use std::os::unix::fs::PermissionsExt;
use std::path::PathBuf;
use std::time::{SystemTime, UNIX_EPOCH};

/// A session record written to disk by `pam_sm_open_session`.
///
/// Serialized as JSON to `{session_dir}/{session_id}.json`.
/// Deleted by `pam_sm_close_session` with duration reporting.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SessionRecord {
    /// Cryptographically-random session ID (prmana-{ts}-{rand}).
    pub session_id: String,
    /// Unix username authenticated in this session.
    pub username: String,
    /// JWT ID from the access token (for revocation correlation). Optional — some IdPs omit JTI.
    pub token_jti: Option<String>,
    /// Token expiry as Unix timestamp (seconds since epoch).
    /// Used to determine if a session has outlived its token.
    pub token_exp: i64,
    /// Session start time as Unix timestamp (seconds since epoch).
    /// Used to compute session duration when the record is deleted.
    pub session_start: i64,
    /// Client IP address from PAM_RHOST. Optional — may be absent in non-SSH contexts.
    pub client_ip: Option<String>,
    /// PID of the sshd process that opened this session.
    pub sshd_pid: u32,
    /// OIDC issuer URL that issued the token.
    pub issuer: String,
}

/// Current Unix timestamp in seconds.
fn now_unix_secs() -> i64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_secs() as i64
}

/// Validate a session ID for safe use as a filesystem path component.
///
/// A session ID must not contain:
/// - Path separator `/`
/// - Null byte `\0`
/// - Parent directory component `..`
/// - Be empty
///
/// Valid characters are ASCII alphanumeric, `-`, and `_`.
/// Session IDs generated by [`crate::security::session::generate_secure_session_id`]
/// are always valid by construction.
fn validate_session_id(session_id: &str) -> io::Result<()> {
    if session_id.is_empty() {
        return Err(io::Error::new(
            io::ErrorKind::InvalidInput,
            "session_id must not be empty",
        ));
    }
    if session_id.contains('/') || session_id.contains('\0') || session_id == ".." {
        return Err(io::Error::new(
            io::ErrorKind::InvalidInput,
            "session_id contains invalid characters (path traversal rejected)",
        ));
    }
    // Allow only alphanumeric, hyphen, and underscore.
    // Session IDs from generate_secure_session_id use hex + hyphens so this is safe.
    let valid = session_id
        .chars()
        .all(|c| c.is_ascii_alphanumeric() || c == '-' || c == '_' || c == '.');
    if !valid {
        return Err(io::Error::new(
            io::ErrorKind::InvalidInput,
            "session_id contains characters outside allowed set [a-zA-Z0-9_.-]",
        ));
    }
    Ok(())
}

/// Ensure the session directory exists with 0700 permissions.
///
/// Creates the directory (and any missing parents) if absent. Idempotent.
/// The directory is expected to be owned by root when the PAM module runs as root.
///
/// # Errors
///
/// Returns `io::Error` if directory creation or permission-setting fails.
pub fn ensure_session_dir(dir: &str) -> io::Result<()> {
    let path = std::path::Path::new(dir);
    if !path.exists() {
        fs::create_dir_all(path)?;
    }
    fs::set_permissions(path, fs::Permissions::from_mode(0o700))?;
    Ok(())
}

/// Write a session record atomically to `{dir}/{session_id}.json`.
///
/// The write is atomic on the same filesystem:
/// 1. Write JSON to `{dir}/{session_id}.json.tmp` with 0600 permissions.
/// 2. Rename `.tmp` to `.json` (rename(2) is atomic within the same directory).
///
/// # Errors
///
/// - `InvalidInput` if `session_id` contains path-traversal characters.
/// - Any I/O error from the underlying filesystem operations.
pub fn write_session_record(dir: &str, session_id: &str, record: &SessionRecord) -> io::Result<()> {
    validate_session_id(session_id)?;

    let dir_path = std::path::Path::new(dir);
    let tmp_path: PathBuf = dir_path.join(format!("{session_id}.json.tmp"));
    let final_path: PathBuf = dir_path.join(format!("{session_id}.json"));

    // Serialize to JSON
    let json = serde_json::to_string(record).map_err(|e| {
        io::Error::new(
            io::ErrorKind::InvalidData,
            format!("Failed to serialize session record: {e}"),
        )
    })?;

    // Write to temp file with 0600 permissions set atomically at creation.
    // Security (Codex finding 5): Using OpenOptions with mode 0600 eliminates
    // the TOCTOU race between File::create() and set_permissions().
    {
        use std::os::unix::fs::OpenOptionsExt;
        let mut file = fs::OpenOptions::new()
            .write(true)
            .create(true)
            .truncate(true)
            .mode(0o600)
            .open(&tmp_path)?;
        file.write_all(json.as_bytes())?;
        file.flush()?;
    }

    // Atomic rename
    fs::rename(&tmp_path, &final_path)?;

    Ok(())
}

/// Read and delete the session record for `session_id`.
///
/// Returns `Ok(Some(record))` if the file was found and deleted.
/// Returns `Ok(None)` if the file did not exist (graceful — not a panic).
/// Returns `Err` on I/O errors other than `NotFound`.
///
/// The caller should compute `now() - record.session_start` to get session duration.
pub fn delete_session_record(dir: &str, session_id: &str) -> io::Result<Option<SessionRecord>> {
    validate_session_id(session_id)?;

    let path: PathBuf = std::path::Path::new(dir).join(format!("{session_id}.json"));

    let json = match fs::read_to_string(&path) {
        Ok(content) => content,
        Err(e) if e.kind() == io::ErrorKind::NotFound => return Ok(None),
        Err(e) => return Err(e),
    };

    // Remove the file before returning. Best-effort: log at WARN if removal fails,
    // but still return the parsed record so callers can emit the audit event.
    if let Err(e) = fs::remove_file(&path) {
        if e.kind() != io::ErrorKind::NotFound {
            tracing::warn!(
                session_id,
                error = %e,
                "Failed to delete session record file; file may be left on disk"
            );
        }
    }

    let record: SessionRecord = serde_json::from_str(&json).map_err(|e| {
        io::Error::new(
            io::ErrorKind::InvalidData,
            format!("Failed to deserialize session record: {e}"),
        )
    })?;

    Ok(Some(record))
}

/// Compute session duration in seconds between `session_start` and now.
pub fn session_duration_secs(session_start: i64) -> i64 {
    now_unix_secs() - session_start
}

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::expect_used)]
mod tests {
    use super::*;
    use std::os::unix::fs::MetadataExt;
    use tempfile::TempDir;

    fn make_record(session_id: &str) -> SessionRecord {
        SessionRecord {
            session_id: session_id.to_string(),
            username: "alice".to_string(),
            token_jti: Some("jti-abc123".to_string()),
            token_exp: 9_999_999_999,
            session_start: now_unix_secs(),
            client_ip: Some("192.168.1.50".to_string()),
            sshd_pid: 12345,
            issuer: "https://idp.example.com".to_string(),
        }
    }

    // ── Session directory ──────────────────────────────────────────────────

    #[test]
    fn test_ensure_session_dir_creates_with_0700() {
        let tmp = TempDir::new().unwrap();
        let dir = tmp.path().join("sessions");
        let dir_str = dir.to_str().unwrap();

        ensure_session_dir(dir_str).unwrap();

        assert!(dir.is_dir());
        let meta = fs::metadata(&dir).unwrap();
        let mode = meta.mode() & 0o777;
        assert_eq!(mode, 0o700, "session dir must be 0700, got {mode:#o}");
    }

    #[test]
    fn test_ensure_session_dir_idempotent() {
        let tmp = TempDir::new().unwrap();
        let dir = tmp.path().join("sessions");
        let dir_str = dir.to_str().unwrap();

        // Call twice — must not error on second call
        ensure_session_dir(dir_str).unwrap();
        ensure_session_dir(dir_str).unwrap();

        assert!(dir.is_dir());
    }

    // ── Write / read round-trip ────────────────────────────────────────────

    #[test]
    fn test_write_session_record_creates_file_with_0600() {
        let tmp = TempDir::new().unwrap();
        let dir_str = tmp.path().to_str().unwrap();
        let session_id = "prmana-test-1234";
        let record = make_record(session_id);

        write_session_record(dir_str, session_id, &record).unwrap();

        let final_path = tmp.path().join(format!("{session_id}.json"));
        assert!(final_path.exists(), "session record file must be created");

        let meta = fs::metadata(&final_path).unwrap();
        let mode = meta.mode() & 0o777;
        assert_eq!(mode, 0o600, "session record must be 0600, got {mode:#o}");
    }

    #[test]
    fn test_write_session_record_no_tmp_file_left() {
        let tmp = TempDir::new().unwrap();
        let dir_str = tmp.path().to_str().unwrap();
        let session_id = "prmana-test-no-tmp";
        let record = make_record(session_id);

        write_session_record(dir_str, session_id, &record).unwrap();

        let tmp_path = tmp.path().join(format!("{session_id}.json.tmp"));
        assert!(!tmp_path.exists(), ".tmp file must be removed after rename");
    }

    #[test]
    fn test_write_delete_roundtrip() {
        let tmp = TempDir::new().unwrap();
        let dir_str = tmp.path().to_str().unwrap();
        let session_id = "prmana-roundtrip";
        let record = make_record(session_id);

        write_session_record(dir_str, session_id, &record).unwrap();
        let recovered = delete_session_record(dir_str, session_id).unwrap();

        let r = recovered.expect("record must be returned on delete");
        assert_eq!(r.session_id, session_id);
        assert_eq!(r.username, "alice");
        assert_eq!(r.token_jti, Some("jti-abc123".to_string()));
        assert_eq!(r.issuer, "https://idp.example.com");

        // File must be gone after delete
        let path = tmp.path().join(format!("{session_id}.json"));
        assert!(
            !path.exists(),
            "file must be deleted after delete_session_record"
        );
    }

    #[test]
    fn test_session_record_serializes_all_fields() {
        let record = make_record("test-session");
        let json = serde_json::to_string(&record).unwrap();

        assert!(json.contains("\"session_id\""), "must have session_id");
        assert!(json.contains("\"username\""), "must have username");
        assert!(json.contains("\"token_jti\""), "must have token_jti");
        assert!(json.contains("\"token_exp\""), "must have token_exp");
        assert!(
            json.contains("\"session_start\""),
            "must have session_start"
        );
        assert!(json.contains("\"client_ip\""), "must have client_ip");
        assert!(json.contains("\"sshd_pid\""), "must have sshd_pid");
        assert!(json.contains("\"issuer\""), "must have issuer");
    }

    #[test]
    fn test_session_record_optional_fields_null() {
        let record = SessionRecord {
            session_id: "test".to_string(),
            username: "bob".to_string(),
            token_jti: None,
            token_exp: 1000,
            session_start: 900,
            client_ip: None,
            sshd_pid: 9999,
            issuer: "https://example.com".to_string(),
        };
        let json = serde_json::to_string(&record).unwrap();
        // token_jti and client_ip should be null
        assert!(json.contains("\"token_jti\":null") || json.contains("\"token_jti\": null"));
        assert!(json.contains("\"client_ip\":null") || json.contains("\"client_ip\": null"));
    }

    // ── Delete non-existent (graceful) ─────────────────────────────────────

    #[test]
    fn test_delete_nonexistent_returns_none() {
        let tmp = TempDir::new().unwrap();
        let dir_str = tmp.path().to_str().unwrap();

        let result = delete_session_record(dir_str, "prmana-nonexistent").unwrap();
        assert!(
            result.is_none(),
            "missing file must return Ok(None), not panic"
        );
    }

    // ── Path traversal rejection ───────────────────────────────────────────

    #[test]
    fn test_write_with_path_traversal_slash_rejected() {
        let tmp = TempDir::new().unwrap();
        let dir_str = tmp.path().to_str().unwrap();
        let record = make_record("x");

        let result = write_session_record(dir_str, "../escape", &record);
        assert!(
            result.is_err(),
            "path traversal via '../escape' must be rejected"
        );
    }

    #[test]
    fn test_write_with_null_byte_rejected() {
        let tmp = TempDir::new().unwrap();
        let dir_str = tmp.path().to_str().unwrap();
        let record = make_record("x");

        let result = write_session_record(dir_str, "valid\0inject", &record);
        assert!(result.is_err(), "null byte in session_id must be rejected");
    }

    #[test]
    fn test_write_empty_session_id_rejected() {
        let tmp = TempDir::new().unwrap();
        let dir_str = tmp.path().to_str().unwrap();
        let record = make_record("x");

        let result = write_session_record(dir_str, "", &record);
        assert!(result.is_err(), "empty session_id must be rejected");
    }

    #[test]
    fn test_write_with_slash_in_session_id_rejected() {
        let tmp = TempDir::new().unwrap();
        let dir_str = tmp.path().to_str().unwrap();
        let record = make_record("x");

        let result = write_session_record(dir_str, "some/path", &record);
        assert!(result.is_err(), "session_id with slash must be rejected");
    }

    #[test]
    fn test_delete_with_path_traversal_rejected() {
        let tmp = TempDir::new().unwrap();
        let dir_str = tmp.path().to_str().unwrap();

        let result = delete_session_record(dir_str, "../etc/passwd");
        assert!(result.is_err(), "path traversal on delete must be rejected");
    }

    // ── Duration helper ────────────────────────────────────────────────────

    #[test]
    fn test_session_duration_secs_positive() {
        let past_start = now_unix_secs() - 120;
        let duration = session_duration_secs(past_start);
        assert!(
            (119..=125).contains(&duration),
            "duration must be approximately 120 seconds, got {duration}"
        );
    }
}
